services:
  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: smart-doc-proxy
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - backend/dev.env
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
